<!DOCTYPE html>
<html lang="en-US">
	<head>
		<meta charset="utf-8" />
		<meta author="tkluge" />
		<meta name="viewport" content="initial-scale=1, width=device-width, maximum-scale=1, minimum-scale=1, user-scalable=no">
		<link href='https://fonts.googleapis.com/css?family=Roboto:300,400' rel='stylesheet' type='text/css'>
		<link rel="stylesheet" type="text/css" href="./css/recover.css">
		<meta name="theme-color" content="#225378">
		<title>Recover</title>
	</head>
	<body>
		<div class="bg-panel"></div>
		<div id="root">
			<div class="forgot" id="modal">
				<div class="progress">
			    	<div class="indeterminate"></div>
			  	</div>
				<section class="input-carousel">
					<div class="carousel-container" id="carousel-container" data-offset="0">
						<div class="carousel-item" id="form-1">
							<header class="modal-header">
								<h1>Reset password</h1>
								<h2 class="subtitle">For account: <?= $email ?></h2>
							</header>
							<input type="hidden" value="<?= $key ?>" id="key" />
							<input type="hidden" value="<?= $email ?>" id="email" />
							<div class="underlined-input">
								<input type="password" name="password" id="password-input" />
								<div class="reacts-to">
									<label class="input-placeholder">Set a password</label>
									<div class="input-underline">
										<div class="input-underline-fill"></div>
									</div>
								</div>
							</div>
							<span class="carousel-input-error" id="password-error">&emsp;</span>
							<div class="underlined-input">
								<input type="password" name="password2" id="password2-input" />
								<div class="reacts-to">
									<label class="input-placeholder">Confirm password</label>
									<div class="input-underline">
										<div class="input-underline-fill"></div>
									</div>
								</div>
							</div>
							<span class="carousel-input-error" id="password2-error">&emsp;</span>
							<div class="button-row">
								<a href="./">Sign in</a>
								<button class="btn btn-primary" id="btn-finish">
								Reset
								<link class="rippleJS">
								</button>
							</div>
						</div>
					</div>
				</section>
			</div>
		</div>
		<footer class="footer">
			<a href="about/terms">Terms</a>
			<a href="about/privacy">Privacy</a>
			<a href="about/help">Help</a>
		</footer>
	</body>
	<script type="text/javascript" src="./js/recover.bundle.js"></script>
</html>
